apiVersion: v1
kind: Service
metadata:
  name: node3002
spec:
  ports:
    - port: 3002
  type: LoadBalancer
  selector:
    app: node3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node3002
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node3002
  template:
    metadata:
      labels:
        app: node3002
    spec:
      containers:
        - name: node3002
          image: conditional-port-dock
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 3002
          env:
            - name: test
              value: "2"
