apiVersion: v1
kind: Service
metadata:
  name: node3001
spec:
  ports:
    - port: 3001
  type: LoadBalancer
  selector:
    app: node3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node3001
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node3001
  template:
    metadata:
      labels:
        app: node3001
    spec:
      containers:
        - name: node3001
          image: conditional-port-dock
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 3001
          env:
            - name: test
              value: "1"
